### ISSUE TITLE
Support for sqlcmd scripting variables

### ISSUE THREAD

**Issue by AaronMurrell** [RamblingCookieMonster/PowerShell#11]
This is not so much an issue but a question but I couldn't find a better place to ask.  Does invoke-sqlcmd2 have any provision for dealing with sqlcmd scripting variables?  To clarify, these are used in the following way with invoke-sqlcmd:

$MyArray = "MyVar1 = 'String1'", "MyVar2 = 'String2'"
Invoke-Sqlcmd -Query "SELECT `$(MyVar1) AS Var1, `$(MyVar2) AS Var2;" -Variable $MyArray

Notice these are not the same thing as what is allowed via the -SqlParameters parameter where the usage is as follows:

    .PARAMETER SqlParameters
        Hashtable of parameters for parameterized SQL queries.  http://blog.codinghorror.com/give-me-parameterized-sql-or-give-me-death/
        Example:
            -Query "SELECT ServerName FROM tblServerInfo WHERE ServerName LIKE @ServerName"
            -SqlParameters @{"ServerName = "c-is-hyperv-1"}

**Comment by RamblingCookieMonster** [comment]
Hi Aaron!

I don't believe so.  It might be worth checking with @ctrlbold, @MikeShepard, or other folks with more SQL Server / PowerShell experience.

I could be way off base, as this isn't my area of expertise but... these seem like they allow parameterized queries, without the safety that parameterized queries give you, and with some fairly ugly syntax. Is there another use for them? No offense intended, completely understand if you have a valid technical or political reason for using them : )

Cheers!

**Comment by martin9700** [comment]
Just my .02, but the queries are simply strings.  Have you considered doing your character replacement in PowerShell prior to submitting the query?

**Comment by MikeShepard** [comment]
I'm not in favor of using the sqlcmd scripting variables.  Actual parameters are much safer.

I imagine if you have queries that use them they would be fairly simple to change to use real parameters.

**Comment by RamblingCookieMonster** [comment]
Hi!

Still have some things to sort out, but moved [Invoke-SqlCmd2 to the SQLCollaborative org](https://github.com/sqlcollaborative/Invoke-SqlCmd2) - If there's more to discuss, feel free to open this there - closing it out for now, sounds like we should stick with parameters as they are

Cheers!
