### ISSUE TITLE
Invoke-SqlCmd2: Support for Encrypt=True in Connection String

### ISSUE THREAD

**Issue by mattmcnabb** [RamblingCookieMonster/PowerShell#13]
This should support encrypting the connection to SQL server when using a username and password. I've briefly tested this and simply added a switch parameter -Encrypt and one more field to the connection string:

`if ($Credential)
 {
     $ConnectionString = "Server={0};Database={1};User ID={2};Password=`"{3}`";Trusted_Connection=False;Connect Timeout={4};Encrypt={5}" -f $SQLInstance,$Database,$Credential.UserName,$Credential.GetNetworkCredential().Password,$ConnectionTimeout,[bool]$Encrypt
}`

Thoughts?

BTW, thanks for this function - I have used it quite a bit!

**Comment by martin9700** [comment]
I'm thinking encryption should be the default, with a -NoEncrypt parameter for SQL servers that don't support/work with.

**Comment by RamblingCookieMonster** [comment]
Hi!

Good catch. I'm usually a fan of secure defaults, but would probably want to roll this in so that it continues to work as a drop in replacement, than can have a switch flipped to use SSL.

Might be worth adding TrustServerCertificate in conjunction with this.

Have some work I'm trying to get through before the summit; might not get to this until next week, unless you want to send a quick PR?

Thanks!

Warren

**Comment by martin9700** [comment]
Yeah, on further research it just seems that most wouldn't have this capability configured so adding it is probably good.  Maybe use the TrustServerCertificate in conjunction with the -Encrypt param.

**Comment by mattmcnabb** [comment]
Warren,

I'll take a look and see if I can get this added in today or tomorrow.

Thanks!

**Comment by mattmcnabb** [comment]
Added in PR #14. I made changes to both Invoke-SqlCmd2 and New-SqlConnection. I'm looking into adding TrustServerCertificate per Martin's suggestion, but that will probably be a new PR.

**Comment by RamblingCookieMonster** [comment]
Merged - thanks Matt!

**Comment by RamblingCookieMonster** [comment]
Hi!  Not sure if there's more to do, but FYI, moved [Invoke-SqlCmd2 to the SQLCollaborative org](https://github.com/sqlcollaborative/Invoke-SqlCmd2).

Closing this out, if there's more to do, feel free to re-open the issue there!

Cheers!
