### ISSUE TITLE
Invoke-Sqlcmd2 cannot pass parms to stored procedure

### ISSUE THREAD

**Issue by rwyoung01** [RamblingCookieMonster/PowerShell#21]
I cannot call a stored procedure with parms.  here is my code
$QUERY = 'EXEC DBATools.dbo.DatabaseRestore @dbname,@backupPath,@restoreDBname'

Invoke-Sqlcmd2 -ServerInstance $s -QueryTimeout 2700 -ConnectionTimeout 0 -Query $QUERY -SqlParameters @{dbname = "SE_Prod";backupPath = "\\dbabackup\SQL_Server_Backups\SQLPRD02$SE\SE_PROD\FULL\";restoreDBname = "SE_SBX"}

**Comment by rwyoung01** [comment]
I fixed the problem.  the backupPath parm contained a $ in the name.  I had the string in double quotes which would remove the value.  Changed to a single quote and now it works

**Comment by RamblingCookieMonster** [comment]
Awesome, thanks for the heads up!  Closing this out.  On a side note, if you do run into issues hit us up at the [dbatools repo](https://github.com/sqlcollaborative/dbatools), where we've moved Invoke-SqlCmd2
