### ISSUE TITLE
[Feature Request] Invoke-sqlcmd2  - offer applicationname parameter

### ISSUE THREAD

**Issue by mbourgon** [RamblingCookieMonster/PowerShell#27]
I use invoke-sqlcmd2 a bunch, and wound up modifying an old version to have applicationname as a variable.  That way I can find it on traces more easily, and can rename it depending on what process is using it, so that if people are looking in sp_whoisactive or the like, they see not just what it's doing, but what project it's a part of.

**Comment by mbourgon** [comment]
It looks like it's already in there ($ApplicationName), I'm just unfamiliar enough with parameter syntax that I'm unsure how to add it.  Here's what it looks like on my version of the old invoke-sqlcmd:
    [Parameter(Position=9, Mandatory=$false)] [string]$ApplicationName='invoke-sqlcmd2'

**Comment by RamblingCookieMonster** [comment]
Hiyo!

Much of this is already in place over in the new home for Invoke-Sqlcmd2, just waiting on a pull request here:

https://github.com/sqlcollaborative/Invoke-SqlCmd2/pull/16

Cheers!
