### ISSUE TITLE
Invoke-Parallel should respect Ctlr+C

### ISSUE THREAD

**Issue by vors** [RamblingCookieMonster/PowerShell#3]
Try to run this and break with `Cltr+C`:

```powershell
(0..1) | Invoke-Parallel -ScriptBlock { 
    $instance = $_
    (1..10) | % {
        Write-Host "Hello from $instance : $_"    
        sleep 1
    }
}
```

![image](https://cloud.githubusercontent.com/assets/816680/5810006/45c0797e-9ff4-11e4-8f33-7a8cf3a701ce.png)

PS: I think that `Invoke-Parallel.ps1` is pretty useful, but it needs some improvements. Would you like to pull it to a separate repo to allow better collaboration?

**Comment by RamblingCookieMonster** [comment]
Added Try/Finally to catch the Ctrl+C and clean up.  Might be a better implementation.
