### ISSUE TITLE
SQL Parameters

### ISSUE THREAD

**Issue by FrankHaarlem** [RamblingCookieMonster/PowerShell#4]
I have addd a SQLParameter conform your example.
But Ik keep getting an error: 
Missing ')' in function parameter list.
At E:\BIT\APPS\POBBR\Scripts\EMF\Invoke-Sqlcmd2-nieuw.ps1:31 char:16
+ $SqlParameters  <<<< @{"AantalUren" = -169},
    + CategoryInfo          : ParserError: (CloseParenToken:TokenId) [], Parse
   Exception
    + FullyQualifiedErrorId : MissingEndParenthesisInFunctionParameterList

My full code is:
$SqlParameters @{"AantalUren" = -169},
[Parameter( Position=8,Mandatory=$false )][switch]

I have also tried to replace it by the following options
$SqlParameters @{"AantalUren = -169"},
$SqlParameters (@{"AantalUren" = -169}),
$SqlParameters @{("AantalUren" = -169)},

But I'm still missing ')'
My query is:
select CAST((DATEADD(hour, $AantalUren, getdate())) AS smalldatetime)

I have also tried to ad the () in my query but no result.
select CAST((DATEADD(hour, $(AantalUren), getdate())) AS smalldatetime)

Can you give me the right code?

**Comment by RamblingCookieMonster** [comment]
Hi!

Rather than using the PowerShell syntax in the SQL query, try something like this:

```
select CAST((DATEADD(hour, @AantalUren, getdate())) AS smalldatetime)
```

You could call using syntax similar to this:

Invoke-Sqlcmd2 -ServerInstance Something -Database Something -Query 'SELECT CAST((DATEADD(hour, @AantalUren, getdate())) AS smalldatetime)' -SqlParameters @{AantalUren = -169}

Cheers!

**Comment by FrankHaarlem** [comment]
Thank you for the answer, now it works fine!
By the way I didn't try to add the powershell context in the sql query but I tried to change the Invoke-Sqlcmd2.ps1
I will close this issue.

**Comment by FrankHaarlem** [comment]
It works fine with one parameter, but now I need 2 parameters.
How do I repeat the parameter in the powerscript file?
Ik have tried -SqlParameters @{AantalUren = 169}  -SqlParameters@{StartUren = 0}
But I can only use -SqlParameters once.
So I have tried the following options:
-SqlParameters @{AantalUren = 169 StartUren = 0}
-SqlParameters @{AantalUren = 169 , StartUren = 0}
-SqlParameters @{(AantalUren = 169 , StartUren = 0)}
-SqlParameters (@{AantalUren = 169} , @{StartUren = 0})
But none of them works.

**Comment by RamblingCookieMonster** [comment]
Hi Frank!

Try something like this:

```powershell
#on one line, use semi-colon
Invoke-Sqlcmd2 ..... -SqlParameters @{AantalUren = -169; StartUren = 0}

#alternatively, use multi-line, no semi-colon needed
Invoke-Sqlcmd2 ..... -SqlParameters @{
    AantalUren = -169
    StartUren = 0
}
```

I typically use the latter, a bit easier to read for me.

Cheers!

**Comment by FrankHaarlem** [comment]
Thanks again, the semicolon works fine.
In this case I prefer the semicolon because I have a list of 20 queries to execute.
So I call the Invoke-Sqlcmd2 20 times and in this case 1 line for each call is easier tot read.
