### ISSUE TITLE
Invoke-SqlCmd2: DataTable Object PowerShell v5 Preview

### ISSUE THREAD

**Issue by jakedenyer** [RamblingCookieMonster/PowerShell#8]
Warren - 

There must have been a recent update to PowerShell v5 that messes with the DataTable object. Here is the issue I had and how I was able to work around it.

WARNING: Exception: Cannot process argument transformation on parameter 'DataTable'. Cannot convert the "System.Object[]" value of type "System.Object[]" to type
"System.Data.DataTable"..ExceptionMessage

$Data = Invoke-Sqlcmd2 -ServerInstance $env:ComputerName -Database $database -query $query -as DataTable

This is where the issue was happening
$Data.Columns.Add("ID", [int]) | Out-Null

When I would try to add a column to the object, it would bomb and say that there was no overload for 2 arguments.

I did some digging and found that if I changed the Invoke-Sqlcmd2 -As switch to DataSet and manually set the $Data variable to $Data.Tables - I was then able to Add columns again. 

This operation was working 2 weeks ago but started giving me issues last week. 

Just thought I would give you a heads up.

**Comment by RamblingCookieMonster** [comment]
Hi Jake!

Haven't had a SQL Server to test this out on - do you by any chance have PowerShell 5 RTM? Will try to test this out on my side time permitting, but we don't have as many SQL Servers at $newjob

Thanks!

**Comment by RamblingCookieMonster** [comment]
Closing this out for now - if this is still an issue, [the sqlcollaborative repo](https://github.com/sqlcollaborative/Invoke-SqlCmd2/) is a good spot for it - cheers!
